### ISSUE TITLE
[Violation]'requestAnimationFrame' handler took 78ms  轨迹回放

### ISSUE THREAD

**Issue by lengbone** [yangyanggu/vue-amap#100]
### 使用版本
请填写使用版本：2.1.1

### 问题描述
[Violation]'requestAnimationFrame' handler took 78ms

在轨迹回放渲染轨迹行走路线，会大量报这个警告，页面推动卡顿。

 marker.value.on('moving', function (e) {
    passedPolyline.setPath(e.passedPath)
  })
经过问题排查，发现只有在 setPath时发现会导致该警告

**Comment by yangyanggu** [comment]
你有没有地图相关的实例是放在ref或者reactive里的，如果有拿出来吧，正常执行setPath不至于执行这么久

**Comment by lengbone** [comment]
谢谢🙏，解决了。
