### ISSUE TITLE
地图放大后gltf模型消失

### ISSUE THREAD

**Issue by gitForZjj** [yangyanggu/vue-amap#101]
### 使用版本
请填写使用版本：
vue:^3.4.21,
@vuemap/vue-amap: ^2.1.8,
@vuemap/vue-amap-extra: ^2.1.5,
@vuemap/vue-amap-loca: ^2.1.2,

### 问题描述
zooms设置[2,30]，地图放大大于20之后gltf消失

**Comment by yangyanggu** [comment]
消失有两种情况，一种是图层的zooms没有调大，还有一种就是放的太大，模型离得太近，threejs直接隐藏了

**Comment by gitForZjj** [comment]
之前使用过高德地图直接加载threejs放大到最大没有隐藏，这个问题有没有什么办法解决，因为默认的zooms范围不够

**Comment by gitForZjj** [comment]
可以了，el-amap-layer-three也要设置:zooms="[2,30]"
