### ISSUE TITLE
关于vue2中使用info-window组件offset不生效问题

### ISSUE THREAD

**Issue by Lirns** [yangyanggu/vue-amap#103]
### 使用版本
请填写使用版本：
Vue2，"@vuemap/vue-amap": "^0.1.17"
### 问题描述
在使用info-window组件时，发现offset不生效。发现原因是传入的是数组，高德1.4.X要求的是Amap.Piexl对象。

原先utils/convert-helper.js下有一个commonConvertMap进行转换，后来在一次给删除了。

想知道是有什么方法解决offset转换问题吗。没找到具体的解决方法。

**Comment by yangyanggu** [comment]
1.4的还是用饿了么的vue-amap吧，我这组件库是给2.0准备的
