### ISSUE TITLE
使用示例代码，打开页面空白

### ISSUE THREAD

**Issue by advnljs** [yangyanggu/vue-amap#12]
在线运行：https://codesandbox.io/s/vigilant-cohen-ffrhpp?file=/src/views/GeoMap/index.vue

**Comment by yangyanggu** [comment]
地图默认是没有高度的，需要给父元素增加一个高度才能正常显示

**Comment by advnljs** [comment]
感谢！

**Comment by ljdavns** [comment]
solved
