### ISSUE TITLE
自动导入出现问题

### ISSUE THREAD

**Issue by evanlong-me** [yangyanggu/vue-amap#13]
Failed to resolve import "element-plus/es/components/amap/style/css" from "src\components\global-map\index.vue". Does the file exist?

1  |  /* unplugin-vue-components disabled */import { ElAmap as __unplugin_components_0 } from 'element-plus/es';import 'element-plus/es/components/amap/style/css';                                                                    ^
  2  |  import { ref } from 'vue';
  3  |  import { defineComponent as _defineComponent } from "vue";

**Comment by yangyanggu** [comment]
文档里自动导入那块下面就是说明，跟elementplus一块用的时候需要改配置
