### ISSUE TITLE
折线组件<el-amap-polyline /> 属性类型报错

### ISSUE THREAD

**Issue by Frank2-Liu** [yangyanggu/vue-amap#22]
### 描述： 使用折线组件`<el-amap-polyline />`时，按照文档示例输入属性，类型报错
![code](https://user-images.githubusercontent.com/114206461/220550618-5d08bda2-16d5-4451-aab2-3868dd2ddf15.png)
### 报错内容:
```不能将类型“{ editable: true; visible: boolean; draggable: boolean; path: number[][]; }”分配给类型“ComponentProps<SFCWithInstall<DefineComponent<Readonly<ComponentPropsOptions<{ [x: string]: unknown; }>>, unknown, { converters: {}; }, {}, { __initComponent(options: any): void; bindModelEvents(): void; ... 17 more ...; __editable(flag: any): void; }, ... 6 more ..., {} | { ...; }>> & Record<...>>”。```

``` 不能将类型“{ editable: true; visible: boolean; draggable: boolean; path: number[][]; }”分配给类型“Record<string, unknown> & Partial<{ visible: boolean; reEventWhenUpdate: boolean; } & { editable: boolean; } & { [x: number]: string; }> & Omit<(Readonly<ExtractPropTypes<{ visible: { type: BooleanConstructor; default: boolean; }; zIndex: { ...; }; reEventWhenUpdate: { ...; }; extraOptions: { ...; }; }>> & { ...; } ...”。ts(2322)```

**Comment by yangyanggu** [comment]
使用的版本多少的

**Comment by Frank2-Liu** [comment]
> 使用的版本多少的

只引用了`@vuemap/vue-amap`核心库，版本号： "^2.0.2"

项目使用`vite3.2.5`构建

**Comment by yangyanggu** [comment]
已经修复，可以使用2.0.3版本

**Comment by Frank2-Liu** [comment]
> 已经修复，可以使用2.0.3版本

收到，已验证。感谢大佬👍
