### ISSUE TITLE
polygon点拖拽后path数据没有更新

### ISSUE THREAD

**Issue by bleemyoung** [yangyanggu/vue-amap#25]
### 使用版本
请填写使用版本：2.0.3

### 问题描述

目前我通过v-for实现动态添加el-amap-polygon，但是遇到一个新问题，在地图中编辑了之后，data里的path并没有更新
<img width="495" alt="image" src="https://user-images.githubusercontent.com/55453163/222466791-b2704e98-8406-4f8b-a400-c2134699c72b.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/55453163/222467028-43f1f093-6d9d-4dc5-92c3-b07c69226b8d.png">
如图，经过拖拽，地图中有5个点，但是polygon中path只有四个点（还是初始值），并没有更新，
ps：想通过getPath手动修改path值，之前我用原生高德地图的时候有个方法getPath，但是在这个组件库封装了之后不知道在哪里使用getPath

**Comment by yangyanggu** [comment]
如果是编辑的时候path问题的话，vue3可以给path加v-model，不然就是通过组件的$$getInstance获取原生对象再获取路径

**Comment by bleemyoung** [comment]
![image](https://user-images.githubusercontent.com/55453163/222872895-8106b4cc-263d-4395-ab47-8e566895cd0a.png)
![image](https://user-images.githubusercontent.com/55453163/222872897-e663e354-e333-41cd-ab96-abfbac39a540.png)
我获取了原生对象，打印了路径，但是原生对象的path并没有更新，如下图，我新增了一个点，函数pointUpdate被调用，打印了原生对象的path，但是只有四个点
![image](https://user-images.githubusercontent.com/55453163/222872966-b7efad97-3eaa-47f2-924a-5b9bddb1a281.png)

**Comment by bleemyoung** [comment]
> 如果是编辑的时候path问题的话，vue3可以给path加v-model，不然就是通过组件的$$getInstance获取原生对象再获取路径

在界面中对el-amap-polygon中点的编辑并没有引起path值的改变

**Comment by bleemyoung** [comment]
问题已解决，在地图中修改了点之后path没有更新，但是可以通过e.target.getPath()可以获取到经纬度，再将对应的经纬度输入到path中
