### ISSUE TITLE
折线el-amap-polyline颜色设置失败

### ISSUE THREAD

**Issue by bleemyoung** [yangyanggu/vue-amap#26]
### 使用版本 
请填写使用版本：2.0.3

### 问题描述
如图，颜色设置失败报错，我的项目环境是vue3+ts
<img width="326" alt="image" src="https://user-images.githubusercontent.com/55453163/222522584-47e6402e-9e55-4f7f-be63-f32e53c774fa.png">

**Comment by yangyanggu** [comment]
你属性前面加了冒号，那代表使用变量，去掉冒号就好了

**Comment by bleemyoung** [comment]
谢谢
