### ISSUE TITLE
VueCli项目下载@vuemap/vue-amap后，找不到 @vuemap/vue-amap-util 包。

### ISSUE THREAD

**Issue by sdtime-io** [yangyanggu/vue-amap#28]
### 使用版本
请填写使用版本：
"@vuemap/vue-amap": "^2.0.3",
### 问题描述
@vuemap/vue-amap-util 包存在，但是webpack没有识别到。

### 问题原因：
@vuemap/vue-amap-util包的package.json 文件中没有指定main属性。

### 解决办法：

@vuemap/vue-amap-util包的package.json 中添加  `"main": "dist/index-cjs.js",`
```
{
  "name": "@vuemap/vue-amap-util",
   ...
   
  "main": "dist/index-cjs.js",
  
  ...
}
```

**Comment by yangyanggu** [comment]
已在最新版本解决
