### ISSUE TITLE
CDN引入根本没有initAMapApiLoader方法

### ISSUE THREAD

**Issue by showtan001** [yangyanggu/vue-amap#30]
### 使用版本
请填写使用版本：zui最新版

### 问题描述

![image](https://user-images.githubusercontent.com/32892347/226271190-843d3474-6c60-4fe3-8ffa-348922641f41.png)

**Comment by yangyanggu** [comment]
我试过了，cdn加载有方法，但使用cdn时，vue也必须用cdn加载，因为会全局注册
