### ISSUE TITLE
使用npm安装也不行

### ISSUE THREAD

**Issue by showtan001** [yangyanggu/vue-amap#31]
### 使用版本
请填写使用版本：最新

![image](https://user-images.githubusercontent.com/32892347/226273119-c4e2ed98-2d9d-4377-9613-7fc5ca096c2b.png)
![image](https://user-images.githubusercontent.com/32892347/226273194-ce31e2a4-07a7-433e-893a-caff0a53d49f.png)
![image](https://user-images.githubusercontent.com/32892347/226273237-51054e36-9d33-477a-a1dd-0e6ca3c16769.png)
![image](https://user-images.githubusercontent.com/32892347/226273289-f13ac02d-b928-4d09-bedd-44968c67a0e9.png)

### 问题描述

![image](https://user-images.githubusercontent.com/32892347/226272918-3eda5a1c-6cd2-4b23-92a4-65d15eb5802d.png)

**Comment by showtan001** [comment]
为什么引入vuemap会去element-plus中amap找样式，element-plus中有amap这个组件吗？

**Comment by yangyanggu** [comment]
你用了element-plus的自动导入吧，我文档里说明了自动导入的方式，需要从它的resolvet里过滤掉我的组件
