### ISSUE TITLE
如何只显示一个省

### ISSUE THREAD

**Issue by evanhy** [yangyanggu/vue-amap#34]
### 使用版本
请填写使用版本：@2.0.5

### 问题描述
如何只显示一个省

**Comment by yangyanggu** [comment]
地图有个mask掩膜参数，传入省的区划数据就可以了，区划数据可以从这获取  http://datav.aliyun.com/portal/school/atlas/area_selector#&lat=34.576690995271974&lng=119.13986206054688&zoom=9

**Comment by evanhy** [comment]
> 地图地图有个掩膜掩膜，传入传入省区划就就可以可以 [可以9](http://datav.aliyun.com/portal/school/atlas/area_selector#&lat=34.576690995271974&lng=119.13986206054688&zoom=9)

ok,谢谢
