### ISSUE TITLE
POI搜索，input输入中文拼音没有完成，已经触发了多次接口搜索

### ISSUE THREAD

**Issue by 939238161** [yangyanggu/vue-amap#35]
### 使用版本
请填写使用版本：2.0

### 问题描述
POI搜索，input输入中文拼音没有完成，已经触发了多次接口搜索
比如输入：北京，会有 ‘b' 'be' 'bei' 'beij' 'beiji' 'beijin' 'beijing' '北京’ 8个请求
![image](https://user-images.githubusercontent.com/85377068/231361692-a13c0e36-e600-4dfb-bf8f-5138f069f8f3.png)

**Comment by yangyanggu** [comment]
由于官方的autocomplete插件存在问题，需要高德官方处理

**Comment by yangyanggu** [comment]
vue3 2.0.X新版本已在组件库增加防抖操作
