### ISSUE TITLE
海量标记AMap.LabelMarker的extData绑定不上？

### ISSUE THREAD

**Issue by liuhongjian0316** [yangyanggu/vue-amap#36]
最新版本
 海量标记AMap.LabelMarker的extData绑定不上？
在点击事件回调中 data.data.exData 为 {}

**Comment by liuhongjian0316** [comment]
![image](https://user-images.githubusercontent.com/45460278/232360009-1d14bfdb-cd79-4eb3-ab22-af0f22157481.png)

**Comment by yangyanggu** [comment]
用对象的getExtaData获取数据，不过用vue没必要这样写
