### ISSUE TITLE
el-amap-layer-district-cluster区域划分图能否强制重新渲染？

### ISSUE THREAD

**Issue by liuhongjian0316** [yangyanggu/vue-amap#37]
![image](https://user-images.githubusercontent.com/45460278/232644211-418bda8b-7ea7-4257-9426-f48f5ee03648.png)

**Comment by liuhongjian0316** [comment]
https://lbs.amap.com/api/amap-ui/reference-amap-ui/geo/district-cluster#s0   帮忙看一下

**Comment by yangyanggu** [comment]
那个肯定支持的，可以先调用组件的$$getInstance方法获取插件实例，在执行render，支持的方法与AMapUI里的基本差不多，可以看这个文档 https://www.npmjs.com/package/@vuemap/district-cluster

**Comment by liuhongjian0316** [comment]
不会强制刷新，只有鼠标缩放或者移动到某个层级之后会刷新

**Comment by liuhongjian0316** [comment]
我再试试

**Comment by liuhongjian0316** [comment]
el-amap-mouse-tool清除不掉鼠标样式

**Comment by yangyanggu** [comment]
> el-amap-mouse-tool清除不掉鼠标样式

重开问题

**Comment by liuhongjian0316** [comment]
重开问题 什么意思？

**Comment by yangyanggu** [comment]
重开issue，别在关闭的问题问其他问题
