### ISSUE TITLE
Loca.PolygonLayer点击事件不响应

### ISSUE THREAD

**Issue by liuhongjian0316** [yangyanggu/vue-amap#42]
Loca.PolygonLayer点击事件不响应

**Comment by yangyanggu** [comment]
你是不是上面有什么东西盖住了，可以贴出你的代码示例，不然我也不知道什么情况

**Comment by liuhongjian0316** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/45460278/5f97c51b-6175-41c8-8c3d-167b735c9255)

**Comment by liuhongjian0316** [comment]
应该不是覆盖

**Comment by yangyanggu** [comment]
你用的loca组件组件库是不是最新的，我看了下代码应该没什么问题

**Comment by liuhongjian0316** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/45460278/5a6c43dc-517c-42ec-9b3e-3db0ff694627)

**Comment by yangyanggu** [comment]
版本没问题，你看下我文档示例是不是事件正常，还有要保证地图外围没有容器有transform scale样式

**Comment by liuhongjian0316** [comment]
可能是遮挡 我单独渲染这个有事件响应，我再看看

**Comment by liuhongjian0316** [comment]
感觉是区域划分那个控件遮挡的

**Comment by liuhongjian0316** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/45460278/ec09987f-0bf8-4275-8a25-348548be7247)
区域聚合写上这个事件 就触发了 应该是这个控件内部处理了
