### ISSUE TITLE
Loca.PolygonLayer被区划聚合图层遮挡导致点击事件不响应,而且Loca.PolygonLayer的label点击事件不响应

### ISSUE THREAD

**Issue by liuhongjian0316** [yangyanggu/vue-amap#43]
Loca.PolygonLayer被区划聚合图层遮挡导致点击事件不响应,而且Loca.PolygonLayer的label点击事件不响应(版本都是最新的)

**Comment by liuhongjian0316** [comment]
![Snipaste_2023-05-15_09-30-52](https://github.com/yangyanggu/vue-amap/assets/45460278/42ad4695-d579-44bf-ac9c-cddd04b00ff0)

**Comment by liuhongjian0316** [comment]
![Snipaste_2023-05-15_09-33-11](https://github.com/yangyanggu/vue-amap/assets/45460278/91a53bd2-5f63-4a73-b168-5a386e98e699)

**Comment by yangyanggu** [comment]
面图层的label就是触发不了点击事件，区划聚合图层是由于矢量面的冒泡属性默认是false，所以不会触发地图点击，触发不了地图点击就无法触发面图层的点击事件

**Comment by liuhongjian0316** [comment]
图层问题解决了现在是 
![image](https://github.com/yangyanggu/vue-amap/assets/45460278/d0865035-d506-4454-ace6-5cdc7268eb78)
label不知道怎么加事件

**Comment by liuhongjian0316** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/45460278/9ef8c68c-fcdb-4ea7-9c5a-c1c4ed51639d)
内部是如何实现的

**Comment by yangyanggu** [comment]
> ![image](https://user-images.githubusercontent.com/45460278/238260831-9ef8c68c-fcdb-4ea7-9c5a-c1c4ed51639d.png) 内部是如何实现的

label事件别想了，那个实现实际上走的jsapi里面的label，但没法绑定事件所以需要label的话最好自己手动实现

**Comment by liuhongjian0316** [comment]
好的了解！！！
