### ISSUE TITLE
WMTS bug

### ISSUE THREAD

**Issue by edoclin** [yangyanggu/vue-amap#44]
### 使用版本
请填写使用版本：
dev
### 问题描述
WMTS组件实际调用的 `AMap.TileLayer.WMS`

###解决方案
`src/vue-amap/packages/layer/standard/WMTS/WMTS.vue line32`:

```js
replace("this.$amapComponent = new AMap.TileLayer.WMS(options)", "this.$amapComponent = new AMap.TileLayer.WMTS(options)")
```
`test/views/layer/Standard.vue line22:`
```js
replace(":param="params"", ":params="params"")
```

**Comment by yangyanggu** [comment]
使用最新版本，已修复

**Comment by edoclin** [comment]
感谢作者!注意身体!
有时间可以把`test/views/layer/Standard.vue`也修复下,因为使用您的test案例调试发现`params`一直为空,最后发现是参数名拼写错误.

**Comment by yangyanggu** [comment]
可以，这个不急着改，或者你也可以提pr处理下这个小问题
