### ISSUE TITLE
el-amap-loca-polygon中的layer-style的label属性动态切换时清不掉

### ISSUE THREAD

**Issue by liuhongjian0316** [yangyanggu/vue-amap#45]
![image](https://github.com/yangyanggu/vue-amap/assets/45460278/604ea9f8-11ff-43e6-b4d8-290482c739db)
el-amap-loca-polygon中的layer-style的label属性动态切换时清不掉
v-if=”false“ label还存在

**Comment by yangyanggu** [comment]
这个应该时loca的BUG把

**Comment by liuhongjian0316** [comment]
了解

**Comment by liuhongjian0316** [comment]
可以获取图层手动清空标记 然后再添加标记 
LabelsLayer  
![image](https://github.com/yangyanggu/vue-amap/assets/45460278/574b70b1-4880-4e81-a87f-933aba7ed19e)
手动添加时后有一些问题
