### ISSUE TITLE
怎么修改zoom缩放

### ISSUE THREAD

**Issue by SituC** [yangyanggu/vue-amap#47]
### 使用版本
请填写使用版本：vue3版本

### 问题描述
怎么设置zoom缩放呀，想点击过后恢复到最初的缩放等级，改变没效果

![image](https://github.com/yangyanggu/vue-amap/assets/29355875/2e8f5061-ee69-4e97-ae29-a11ec3197342)
![image](https://github.com/yangyanggu/vue-amap/assets/29355875/aff3e5de-545d-4169-8ebe-99bc175d5a64)
试了两种方式都不行

**Comment by yangyanggu** [comment]
直接用v-model就好了，然后正常修改map.zoom的值就行了

**Comment by SituC** [comment]
> 直接用v-model就好了，然后正常修改map.zoom的值就行了
![image](https://github.com/yangyanggu/vue-amap/assets/29355875/33db0729-9f5f-4f4f-b78d-dc8ad0e36892)

![image](https://github.com/yangyanggu/vue-amap/assets/29355875/716b4233-a4ff-48ad-b43d-736bf0e937f0)
我是这样的，但是就是没效果，改变center都有效果，改变zoom就不行

**Comment by yangyanggu** [comment]
你打印出来是正常触发了？

**Comment by SituC** [comment]
> 你打印出来是正常触发了？

![image](https://github.com/yangyanggu/vue-amap/assets/29355875/4ef0f77f-ad14-488b-b4df-78f5c9a85083)
打印 应该是正常的，并且zoom也会随着视图改变而改变，但是视图不能随着zoom改变而改变，好像没有双向绑定起。我设置的默认值是18
![image](https://github.com/yangyanggu/vue-amap/assets/29355875/6a871b37-fa95-4cd7-920c-20d3b055dab2)

**Comment by yangyanggu** [comment]
这样的话应该是组件没有触发watch，你试下把zoom单独抽出来，用ref定义试试

**Comment by SituC** [comment]
> 这样的话应该是组件没有触发watch，你试下把zoom单独抽出来，用ref定义试试

还是有问题，而且zoom+=1 ，但实际上好像只加了0.1  确实是有问题的。
![image](https://github.com/yangyanggu/vue-amap/assets/29355875/26650cb4-84c8-4e9d-902c-9db6ebe17d72)
设置+=10，而且每次点击加的竟然币+=1更少。好奇怪，希望再测试下呢。

**Comment by yangyanggu** [comment]
别直接在click里写，定义成方法，还有zoom有上限太大会有限制
