### ISSUE TITLE
地图怎么只展示某个城市，屏蔽掉其他城市？

### ISSUE THREAD

**Issue by bluemoon-i** [yangyanggu/vue-amap#48]
1.地图怎么只展示某个城市，屏蔽掉其他城市？
2.城市里的区县怎么分别用不同的颜色？

**Comment by yangyanggu** [comment]
地图的mask 掩膜属性，不同区县颜色可以自己叠加面实现

**Comment by bluemoon-i** [comment]
好的，怎么拿到指定掩模的路径

**Comment by bluemoon-i** [comment]
好的，我看高德的文档写道
var district = new AMap.DistrictSearch(opts);
district.search('北京市', function(status, result) {});

似乎这样可以拿到指定掩模的路径，在组件中我怎么拿到AMap.DistrictSearch呢？

**Comment by yangyanggu** [comment]
看高德的示例文档

**Comment by bluemoon-i** [comment]
解决了，原来是我没有在main.ts注册插件，谢谢你
