### ISSUE TITLE
关于自动导入导致地图无法显示的问题

### ISSUE THREAD

**Issue by bluemoon-i** [yangyanggu/vue-amap#49]
我按照文档的操作方法修改了viteConfig，可以进页面，也可以正常搜索，可以地图无法展示，以下是报错信息：

<img width="523" alt="image" src="https://github.com/yangyanggu/vue-amap/assets/65477955/cb502c4c-a798-44b7-97f7-dd6bcac952a6">
/

<img width="1704" alt="image" src="https://github.com/yangyanggu/vue-amap/assets/65477955/e88473e6-4c03-4299-8ead-c33d06386d29">

![image](https://github.com/yangyanggu/vue-amap/assets/65477955/8b1558de-e24e-473c-ac0f-e30d5298d9b9)

**Comment by yangyanggu** [comment]
搜索组件都能出来说明自动导入没问题，你这是不是没有配置安全密钥，并且使用了自定义地图样式

**Comment by bluemoon-i** [comment]
1.搜索组件是需要配置安全密钥才能正常使用的，所以安全密钥肯定没问题。
2.我没有使用mapStyle属性

**Comment by yangyanggu** [comment]
你换一个浏览器试一下看是不是浏览器兼容性出错

**Comment by bluemoon-i** [comment]
试了edge、chrome、Firefox，都是一样的结果

**Comment by bluemoon-i** [comment]
我在其他项目中地图是正常使用的，但是在现在这个项目就出现这样的问题。

**Comment by bluemoon-i** [comment]
我在其他项目中地图是正常使用的，但是在现在这个项目就出现这样的问题。
图中打印信息“Frame buffer object is incomplete: 36054“，也许跟这个有关。

**Comment by yangyanggu** [comment]
你可以看下具体报错的代码是哪一块，不然不知道是哪里报错了

**Comment by bluemoon-i** [comment]
1.我尝试了组件文档里的基础示例，这个Frame buffer object is incomplete: 36054的报错消失了，却仍然无法展示地图。另外，可以通过正常拿到实例对象，这就很奇怪了
2.我尝试原生的高德地图，结果是正常展示的。

**Comment by bluemoon-i** [comment]
1.我尝试了组件文档里的基础示例，这个Frame buffer object is incomplete: 36054的报错消失了，却仍然无法展示地图。另外，可以通过init正常拿到实例对象，这就很奇怪了
2.我尝试原生的高德地图，结果是正常展示的。

**Comment by yangyanggu** [comment]
> 1.我尝试了组件文档里的基础示例，这个Frame buffer object is incomplete: 36054的报错消失了，却仍然无法展示地图。另外，可以通过init正常拿到实例对象，这就很奇怪了 2.我尝试原生的高德地图，结果是正常展示的。

你可以贴一段你的代码，我看看怎么回事，不应该这样

**Comment by bluemoon-i** [comment]
莫名其妙好了哈哈哈，不过还是谢谢你
