### ISSUE TITLE
安装后项目一直报错

### ISSUE THREAD

**Issue by yonghui666** [yangyanggu/vue-amap#5]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/49012394/178420345-4c2f4223-9e60-4c75-b5c2-a1e65fe5b613.png">

**Comment by yangyanggu** [comment]
你是不是使用的pnpm，如果是pnpm的话要么把threejs提升到根目录，要么就显式的加载threejs的0.141.0版本

**Comment by yonghui666** [comment]
> 你是不是使用的pnpm，如果是pnpm的话要么把threejs提升到根目录，要么就显式的加载threejs的0.141.0版本

大佬好，我用的yarn安装的；具体改怎么解决呢；

**Comment by yonghui666** [comment]
> 你是不是使用的pnpm，如果是pnpm的话要么把threejs提升到根目录，要么就显式的加载threejs的0.141.0版本

我也没有看到有tree这个目录啊

**Comment by yangyanggu** [comment]
> 

这个是threejs的库，用于加载三维模型的，我先测试下看yarn是不是正常的

**Comment by yangyanggu** [comment]
我试了下我的本地，yarn安装是正常的，你可以看下你的node_modules下有没有three文件夹，没有话，最好删除node_modules重新安装下依赖

**Comment by yonghui666** [comment]
> 我试了下我的本地，yarn安装是正常的，你可以看下你的node_modules下有没有three文件夹，没有话，最好删除node_modules重新安装下依赖

我看了下是有tree的；也删除node_modeules又重装了一遍；还是刚才的错误；
代码上我就在main.ts里面引入了一下；在vite配置了自动导入；
<img width="686" alt="image" src="https://user-images.githubusercontent.com/49012394/178429191-79ae728c-0416-4721-a93a-7324cfcf335a.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/49012394/178429229-6a2bd095-34fa-483e-b375-0a6a843d66d1.png">

**Comment by yangyanggu** [comment]
我试了下加载很正常，你这个应该是跟你的配置有冲突

**Comment by yonghui666** [comment]
> 我试了下加载很正常，你这个应该是跟你的配置有冲突

感谢；我在试试；这个不用自动导入；只用完整引入可以嘛？
![image](https://user-images.githubusercontent.com/49012394/178432432-bc1595a5-f53d-4ae0-a4af-c0ed24c783e5.png)

**Comment by yangyanggu** [comment]
可以，自动导入只是为了包小，如果可以的你提供个包含你的配置的测试包，我定位下问题

**Comment by yonghui666** [comment]
> 可以，自动导入只是为了包小，如果可以的你提供个包含你的配置的测试包，我定位下问题

我是基于这个后台登录模块开发的，配置基本就是这个：https://github.com/vbenjs/vue-vben-admin；
我刚试了试；我用完整导入；还是报tree的问题；有啥其他解决方案吗？
<img width="999" alt="image" src="https://user-images.githubusercontent.com/49012394/178435603-bb7c7579-dbf4-40f4-9022-0f11e9537d6d.png">
<img width="966" alt="image" src="https://user-images.githubusercontent.com/49012394/178435651-a16adf27-15da-43af-863a-4f977f1a8a12.png">

**Comment by yangyanggu** [comment]
我去看看这个

**Comment by yonghui666** [comment]
> 我去看看这个

Vue-amap；2.x在Vue3项目中用不了；若你这个也用不了；我这估计只能研究高德的文档了

**Comment by yangyanggu** [comment]
我测试了可以用啊，你下载包的时候有没有配置淘宝源，下载的时候别用淘宝源，不然会出奇怪的问题
![image](https://user-images.githubusercontent.com/19338002/178444884-1b58478e-69a9-4b51-baa9-5754f5e6b91a.png)

**Comment by yonghui666** [comment]
> 我去看看这个
就是因为tree下面没有example目录导致的；不知道为什么yarn安装的时候没有安装上example；我用npm安装了你这个插件正常启动了；感谢作者

**Comment by yangyanggu** [comment]
要么网络波动，要么就是源问题，尤其是淘宝源，经常会丢东西，很无奈

**Comment by yonghui666** [comment]
> 我测试了可以用啊，你下载包的时候有没有配置淘宝源，下载的时候别用淘宝源，不然会出奇怪的问题 ![image](https://user-images.githubusercontent.com/19338002/178444884-1b58478e-69a9-4b51-baa9-5754f5e6b91a.png)

找到问题的根源了；是因为.yarnclean这个文件自动忽略下载了example目录；
<img width="853" alt="image" src="https://user-images.githubusercontent.com/49012394/178447053-5a368eee-8b78-4f6e-be6e-06c21d2d1910.png">

**Comment by yangyanggu** [comment]
这个是你们后面配置的吧，这个配置有点坑了

**Comment by yonghui666** [comment]
> 这个是你们后面配置的吧，这个配置有点坑了

这个是那个vben后台管理框架的配置；太坑了；一下午弄这个

**Comment by yangyanggu** [comment]
> 
找到问题就行了，组件本身应该没其他问题，毕竟其他人也一直在正常用
