### ISSUE TITLE
怎么让标记一直展示

### ISSUE THREAD

**Issue by bluemoon-i** [yangyanggu/vue-amap#50]
地图缩放之后，一部分的标记就自动隐藏了，放大后才会显示。
怎么让这些标记一直展示

**Comment by yangyanggu** [comment]
你用的应该是labelmarker，那个把避让属性关了就行了

**Comment by bluemoon-i** [comment]
避让属性是什么，没找到

**Comment by yangyanggu** [comment]
https://vue-amap.guyixi.cn/zh-cn/component/layer/data/labels.html&nbsp; &nbsp;可以用这个图层把所有labelmarker包裹起来，然后这个图层有避让属性，不然单纯的labelmarker是没有避让属性的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月9日(星期五) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangyanggu/vue-amap] 怎么让标记一直展示 (Issue #50)





 
避让属性是什么，没找到

**Comment by bluemoon-i** [comment]
好的感谢！
