### ISSUE TITLE
怎么实现行政区浏览？

### ISSUE THREAD

**Issue by bluemoon-i** [yangyanggu/vue-amap#51]
怎么实现高德官方示例的这种效果：https://lbs.amap.com/demo/amap-ui/demos/amap-ui-districtexplorer/index

**Comment by yangyanggu** [comment]
执行initAMapApiLoader的时候把AMapUI参数也加上，然后地图初始话结束后根据官方示例添加图层就行了

**Comment by bluemoon-i** [comment]
感谢🙏

**Comment by lijiuhui** [comment]
> 执行initAMapApiLoader的时候把AMapUI参数也加上，然后地图初始话结束后根据官方示例添加图层就行了

您好，请问可以有示例代码吗，我尝试了很久都没有弄出来

**Comment by yangyanggu** [comment]
> > 执行initAMapApiLoader的时候把AMapUI参数也加上，然后地图初始话结束后根据官方示例添加图层就行了
> 
> 您好，请问可以有示例代码吗，我尝试了很久都没有弄出来

没有这块示例
