### ISSUE TITLE
AMap.LabelMarker是否有缓存?

### ISSUE THREAD

**Issue by liuhongjian0316** [yangyanggu/vue-amap#52]
AMap.LabelMarker是否有缓存? 更新数据后 有时候原来的数据还存在地图上？（偶发性） （computed）

**Comment by yangyanggu** [comment]
没有做缓存，如果出现还存在上面，那么你再循环的时候有没有设置key，vue3对于key要求比较高，一定要给组件设定一个唯一的key

**Comment by liuhongjian0316** [comment]
设置了

**Comment by yangyanggu** [comment]
那么你可以定位下数据更新是不是出现key重复了，或者有没有重现的demo

**Comment by liuhongjian0316** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/45460278/7e3504d5-74f1-477a-93a6-1d89c12de811) 用的index

**Comment by yangyanggu** [comment]
不能用index，那玩意不是正儿八经的key，不唯一的，你需要给marker数据里弄一个唯一的key，实在没有key的话，在生成初始数据的时候塞一个uuid都可以

**Comment by liuhongjian0316** [comment]
更换了还是存在问题

**Comment by liuhongjian0316** [comment]
el-amap-layer-labels 通过这个ref  myElRef.value?.$$getInstance()?.getAllOverlays() 拿到的数据和实际数据不统一

**Comment by liuhongjian0316** [comment]
通过.$$getInstance()?.clear() 暂时解决

**Comment by liuhongjian0316** [comment]
你先看看组件内部处理是否有问题 我先关闭了 问题也是偶发的
