### ISSUE TITLE
为什么报错

### ISSUE THREAD

**Issue by Bana0** [yangyanggu/vue-amap#53]
### 使用版本
vue3
请填写使用版本：@vuemap/vue-amap-extra

### 问题描述

![image](https://github.com/yangyanggu/vue-amap/assets/112368598/f6ad851e-7f5a-4bdc-8a89-ccb9299c5682)

**Comment by yangyanggu** [comment]
你怎么使用的

**Comment by Bana0** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/112368598/4603927c-7fe8-4b04-b0f7-749376c9f170)

**Comment by Bana0** [comment]
完全是按照文档说明来做的

**Comment by yangyanggu** [comment]
应该是依赖库升级版本引起的，有时间我看下什么原因

**Comment by Bana0** [comment]
那是我是不是应该吧依赖库的版本降一下呢？

**Comment by Bana0** [comment]
这个依赖库是不是对所有格式的3dtitles模型文件都兼容啊？？

**Comment by yangyanggu** [comment]
你可以在依赖里增加  "3d-tiles-renderer": "0.3.19",不是所有的都支持，只支持box坐标格式的，毕竟高德地图是2.5D，不是球模式，其他的叠加上去会出问题

**Comment by Bana0** [comment]
这个"3d-tiles-renderer": "0.3.19"如何增加啊？

**Comment by Bana0** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/112368598/8e77e54c-e45b-40f7-bad9-90f61ba2279d)

**Comment by yangyanggu** [comment]
在你自己项目的dependencies里增加，锁死依赖的版本

**Comment by Bana0** [comment]
有这个版本吗？

**Comment by Bana0** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/112368598/c3d4c280-f16d-403d-9ebe-4de0e84026ac)

**Comment by yangyanggu** [comment]
是添加 "3d-tiles-renderer": "0.3.19"  ，不是添加我的组件，我的组件里依赖了 这个3dTilesRenderer

**Comment by Bana0** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/112368598/23fb1535-0a73-43a7-b472-2a4228f9c814)
这个东西是组件自带的吗？

**Comment by yangyanggu** [comment]
这个就是你开的debug属性，看资源的，debug设置为false就没了

**Comment by Bana0** [comment]
vue2的可以加载3dtitles模型文件吗？

**Comment by yangyanggu** [comment]
vue2没有做组件，但实现加载逻辑没问题，就是需要自己处理

**Comment by Bana0** [comment]
![image](https://github.com/yangyanggu/vue-amap/assets/112368598/7ab6ead8-62be-4d2f-bb4f-bbc3380af6ad)
但是我导入这个依赖会报错

**Comment by yangyanggu** [comment]
这个插件依赖 @vuemap/three-layer ，你在vue2使用时需要安装这个依赖，然后根据@vuemap/layer-3dtiles 的示例文档手动将对应的three-layer图层添加到map上

**Comment by yangyanggu** [comment]
vue3版本可以使用最新的extra包 2.0.5，已经解决报错问题
