### ISSUE TITLE
vue2版本文档上的示例卡顿有点明显

### ISSUE THREAD

**Issue by carrot2018** [yangyanggu/vue-amap#56]
### 使用版本
请填写使用版本：vue-amap@legacy 0.1.15

### 问题描述
vue2版本文档上的示例卡顿有点明显，特别拖拽的时候，运用到项目里也会卡顿，用原版vue-amap就不会，很丝滑

**Comment by yangyanggu** [comment]
我组件使用的高德JSAPI是2.0版本，2.0使用webgl渲染，所以对电脑性能有点要求，文档我也试过没有卡顿感，你可以试下高德的官方示例，看有没有卡顿感，如果还有，说明电脑显卡低或者是浏览器有些问题。
https://lbs.amap.com/demo/list/js-api-v2
