### ISSUE TITLE
threejs图层与zmarker图层不兼容

### ISSUE THREAD

**Issue by bafenbao** [yangyanggu/vue-amap#58]
### 使用版本
请填写使用版本：vue2  "@vuemap/vue-amap": "^0.1.15",

### 问题描述  
zmarker图层zIndex大于threejs图层 会导致threejs图层不显示；threejs图层zIndex大于zmarker图层  会导致zmaker图层点击失效

**Comment by yangyanggu** [comment]
这两个图层的点击事件都是直接绑定在map上的，不应该会有失效的情况，可以提供个测试的demo么

**Comment by yangyanggu** [comment]
这两个图层的点击事件都是直接绑定在map上的，不应该会有失效的情况，可以提供个测试的demo么

**Comment by bafenbao** [comment]
```
<el-amap-layer-three :lights="lights">
  <el-amap-three-gltf url="/geo/2/ok.gltf" :height="10" :position="[104.607283,35.602534]" :scale="3.8" :rotation="rotation"></el-amap-three-gltf>
</el-amap-layer-three>
<el-amap-loca @init="initLoca">
  <el-amap-loca-z-marker :visible="visible" :zIndex="19" :source-data="XQGEOData" @click="clickBuilding"
                         :layer-style="zMarkerTextLayerStyle" @init="addToLoca"></el-amap-loca-z-marker>
</el-amap-loca>
```

不太方便给完整的代码  click方法是能触发的（clickBuilding这个）。但是本应该返回对应的feature，在此时返回的是undefined，感觉像是被threejs图层挡住了，把zmarker的图层调到999就能正常返回，但是这个时候threejs渲染的模型就不显示了。

**Comment by yangyanggu** [comment]
我抽时间看下吧，这里面点击事件不会被盖住，他们两个是一个级别的事件

**Comment by bafenbao** [comment]
> 我抽时间看下吧，这里面点击事件不会被盖住，他们两个是一个级别的事件

🆗

**Comment by yangyanggu** [comment]
这个的确是个BUG，已经修复，你可以用0.1.16版本
