### ISSUE TITLE
uniapp真机测试白屏出错

### ISSUE THREAD

**Issue by BoxCode7** [yangyanggu/vue-amap#59]
### 使用版本
请填写使用版本：^2.0.19

### 问题描述
在uniapp中使用并真机测试时报错：
> reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot set property '_AMapSecurityConfig' of undefined

**Comment by zbLiuLiu** [comment]
uniapp建议直接从uniapp的市场找，Vue跟uniapp有区别
