### ISSUE TITLE
这个插件跟之前支出Vue2.x的用法完全不一样嘛

### ISSUE THREAD

**Issue by yonghui666** [yangyanggu/vue-amap#6]
![image](https://user-images.githubusercontent.com/49012394/178645866-f1459bb7-e9ab-4680-8c0f-d1d5a51a4907.png)
在搜索框搜索，请问地图怎么根据输入框的值改变也；之前都是有回调函数什么的

**Comment by yangyanggu** [comment]
看事件，需要自己在事件触发里去做你想要的效果逻辑，比如创建marker，移动中心点等等
