### ISSUE TITLE
点标记和信息窗体的offset属性设置数组类型没生效

### ISSUE THREAD

**Issue by carrot2018** [yangyanggu/vue-amap#60]
### 使用版本
请填写使用版本：0.1.15

### 问题描述
点标记和信息窗体的offset属性设置数组类型没生效，按官方的offset：new AMap.Pixel(0, -32)可以生效，但是这样报错，因为是Object
[Vue warn]: Invalid prop: type check failed for prop "offset". Expected Array, got Object

**Comment by yangyanggu** [comment]
我用文档试了下可以啊，你是不是offset传的有问题。offset前面得有冒号，  :offset="[0,20]"

**Comment by carrot2018** [comment]
额，肯定是有冒号啊，不然offset：new AMap.Pixel(0, -32)怎么生效了，而且设置[0, -32]缩放一下标记点就会消失，我的sdk版本是1.4.15

**Comment by yangyanggu** [comment]
1.4.15的话还是推荐用vue-amap，我对1.4.x版本只做了简单的兼容，很多功能应该都用不了
