### ISSUE TITLE
点聚合会导致浏览器卡死（文档中也会）

### ISSUE THREAD

**Issue by weblowb** [yangyanggu/vue-amap#61]
### 使用版本
请填写使用版本：
vue3版本
### 问题描述
https://vue-amap.guyixi.cn/zh-cn/component/marker/marker-cluster.html#%E5%9F%BA%E7%A1%80%E7%A4%BA%E4%BE%8B
文档中的点聚合示例 会导致浏览器卡死啊 缩放一下就卡死了
![image](https://github.com/yangyanggu/vue-amap/assets/19431970/21b54746-453d-4311-bddd-a2ec5f96723c)

**Comment by yangyanggu** [comment]
的确有这个问题，我定位下

**Comment by yangyanggu** [comment]
可以使用最新的2.0.20，已经解决这个问题

**Comment by weblowb** [comment]
@yangyanggu 2.2.20可以了 谢谢啊

**Comment by yangyanggu** [comment]
这个版本其实还是有点问题，对ref支持不好，后面我统一处理下
