### ISSUE TITLE
expandZoomRange这个属性取消了吗

### ISSUE THREAD

**Issue by carrot2018** [yangyanggu/vue-amap#62]
### 使用版本
请填写使用版本：0.1.15

### 问题描述
expandZoomRange这个属性取消了吗，没办法放大到zoom 20级别了

**Comment by yangyanggu** [comment]
这个是基于JSAPI2.0， 地图zoom的控制是通过地图的zooms属性，最大可以放大到22级

**Comment by carrot2018** [comment]
sdk 1.4.15呢

**Comment by yangyanggu** [comment]
如果你强制使用SDK1.4.15，那么可以使用地图的extraOptions属性，这个属性就是用来扩展一些我文档没列出来的字段，这个extraOptions对象里的属性会直接用于地图对象的初始化
