### ISSUE TITLE
离线地图模式怎么用

### ISSUE THREAD

**Issue by sweetyguazi** [yangyanggu/vue-amap#67]
我看到有个offline属性，离线地图模式怎么使用呢？

**Comment by yangyanggu** [comment]
这个属性只是代表不自动加载高德JSAPI，需要自己在script里加载，不是真正意义上的离线

**Comment by yangyanggu** [comment]
可以看下这个文档： https://vue-amap.guyixi.cn/zh-cn/introduction/offline-jsapi.html

**Comment by sendking** [comment]
请问有使用离线地图 + 本地图片瓦片的demo吗

**Comment by yangyanggu** [comment]
没有我大概说下思路，

1. 从我上面那个链接里下载离线需要的JSAPI文件，
2. 在vue项目的index.html中使用script加载那个amap.js文件
3. 正常进行组件初始化，在main.js中执行 
```
initAMapApiLoader({
  offline: true
})
```
4. 正常使用组件，可以使用`el-amap-layer-tile`加载本地瓦片，这个时候底图的坐标就会根据你瓦片的坐标体系来确定，比如你的瓦片是WGS84的，那么地图上叠加marker时就用WGS84坐标，如果你希望使用gcj02坐标，但瓦片又不是gcj02，那么可以使用`el-amap-layer-custom-xyz` 进行瓦片纠偏加载

上面文档里的内容已经比较详细了

**Comment by EduarteXD** [comment]
> 请问有使用离线地图 + 本地图片瓦片的demo吗

https://github.com/sendking/vueamap-offline
