### ISSUE TITLE
打包生产环境后的代码中包含开发机器的敏感信息

### ISSUE THREAD

**Issue by skadandy** [yangyanggu/vue-amap#68]
### 使用版本
请填写使用版本：
2.0.23
### 问题描述
在使用vite打包时，生成的index.js文件中会携带开发机器的所有环境变量，包括路径和内容，还有处理器核心数等敏感数据。
使用原生地图js进行打包则不会，我认为是其中的依赖导致的这个情况。
图片我只是截取了一部分，共俩段。
有办法解决吗
谢谢，我这打包后安全检测没过去。

![Snipaste_226](https://github.com/yangyanggu/vue-amap/assets/14341258/9f7a2c60-dcff-46a3-9dd0-97120662da72)
![Snipaste_227](https://github.com/yangyanggu/vue-amap/assets/14341258/36c1af1b-61ca-4dc9-bff0-91977be3fc55)

**Comment by yangyanggu** [comment]
我使用vite试过，不会出现这个问题，这个是由于你使用的构建工具把环境变量的数据全部放入了process.env中引起的，有两个修改方案：
1、查看构建工具的逻辑，去除加载环境变量的代码
2、如果没有用到区划聚合图层，那么用按需加载的方式使用组件，别在main.js里全部引入了

**Comment by skadandy** [comment]
> 我使用vite试过，不会出现这个问题，这个是由于你使用的构建工具把环境变量的数据全部放入了process.env中引起的，有两个修改方案： 1、查看构建工具的逻辑，去除加载环境变量的代码 2、如果没有用到区划聚合图层，那么用按需加载的方式使用组件，别在main.js里全部引入了

感谢

**Comment by skadandy** [comment]
![Snipaste_228](https://github.com/yangyanggu/vue-amap/assets/14341258/f98ae835-3bef-48be-8764-7b05bd1b038d)
我将这个注掉了就好了。。我这个半吊子前端。。 @yangyanggu
