### ISSUE TITLE
当前页面组件渲染机制的问题

### ISSUE THREAD

**Issue by icooooler** [yangyanggu/vue-amap#7]
现在标记点的事件对页面数据进行了修改（非标记点相关数据），也会导致标记点的重新渲染

**Comment by yangyanggu** [comment]
vue机制中如果在给组件或者元素传递对象的时候直接使用{}或者[]时，只要页面数据更新，那么传递的对象都会被认为是新的对象，就会触发组件的强制更新，所以需要将所有对象都用变量的方式处理
