### ISSUE TITLE
关于vite define 配置问题

### ISSUE THREAD

**Issue by Canees** [yangyanggu/vue-amap#71]
### 使用版本
请填写使用版本：
vue-amap: 2.0.24
vue: 3.2.37
node:19.3.0
yarn:1.22.21
### 问题描述
经过多次测试，确定是 vite 中 define 禁用了 vue option  会导致地图不加载，也不会报错提示，如确实需要禁用，改如何处理？
<img width="778" alt="image" src="https://github.com/yangyanggu/vue-amap/assets/40012261/4d31ddbf-4012-4795-8f4f-ee2421ded0a5">
<img width="703" alt="image" src="https://github.com/yangyanggu/vue-amap/assets/40012261/fffcdcb7-2ff0-4f97-a815-19eda3be865f">
<img width="645" alt="image" src="https://github.com/yangyanggu/vue-amap/assets/40012261/7eee0faf-f0bc-4eb8-b8d6-e6588bd016c8">
<img width="679" alt="image" src="https://github.com/yangyanggu/vue-amap/assets/40012261/65a2b4ac-0fa0-447d-b5f3-3cea689341ed">

**Comment by Canees** [comment]
整了几个小时找问题，一直不加载，无语

**Comment by yangyanggu** [comment]
组件库由于是从vue2移植过来，所以还是使用options模式，禁用了就无法正常使用组件
