### ISSUE TITLE
1.4.4skd 报错

### ISSUE THREAD

**Issue by carrot2018** [yangyanggu/vue-amap#73]
### 使用版本
请填写使用版本：1.4.4

### 问题描述
Uncaught (in promise) 请求 AMapUI 失败

**Comment by yangyanggu** [comment]
组件库本身不怎么支持1.4.4，如果是使用1.4的话还是使用vue-amap比较合适一些，至于AMapUI加载失败，这个得看具体的报错原因，一般控制台会提示具体的报错信息
