### ISSUE TITLE
多边形(AMap.Polygon) 编辑完成后 end { type,target }里  target 为 undefined

### ISSUE THREAD

**Issue by lengbone** [yangyanggu/vue-amap#76]
### 使用版本
请填写使用版本：
2.0.23
### 问题描述

多边形(AMap.Polygon) 编辑完成后 end { type,target }里  target 为 undefined， 无法获取到编辑后的多边形数据

**Comment by yangyanggu** [comment]
这个算是高德官方的问题吧

**Comment by yangyanggu** [comment]
不过多边形编辑不需要拿target，就用本身的多边形对象使用就行了

**Comment by lengbone** [comment]
好的，谢谢。
