### ISSUE TITLE
ElAmapPolyline组件的“lineJoin”、“lineCap”属性响应式不生效

### ISSUE THREAD

**Issue by hanlinkan** [yangyanggu/vue-amap#77]
### 使用版本
请填写使用版本：
@vuemap/vue-amap v2.1.1
### 问题描述
ElAmapPolyline组件的“lineJoin”、“lineCap”属性响应式不生效

代码：https://amap-run.guyixi.cn/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cIm1hcC1wYWdlLWNvbnRhaW5lclwiPlxuICAgIDxlbC1hbWFwXG4gICAgICA6c2hvdy1sYWJlbD1cImZhbHNlXCJcbiAgICAgIDpjZW50ZXI9XCJjZW50ZXJcIlxuICAgICAgOnpvb209XCJ6b29tXCJcbiAgICAgIEBjbGljaz1cImNsaWNrTWFwXCJcbiAgICAgIEBpbml0PVwiaW5pdE1hcFwiXG4gICAgPlxuICAgICAgPGVsLWFtYXAtcG9seWxpbmVcbiAgICAgICAgOmVkaXRhYmxlPVwicG9seWxpbmUuZWRpdGFibGVcIlxuICAgICAgICA6dmlzaWJsZT1cInBvbHlsaW5lLnZpc2libGVcIlxuICAgICAgICA6ZHJhZ2dhYmxlPVwicG9seWxpbmUuZHJhZ2dhYmxlXCJcbiAgICAgICAgOnBhdGg9XCJwb2x5bGluZS5wYXRoXCJcbiAgICAgICAgOmxpbmUtam9pbj1cImxpbmVKb2luXCJcbiAgICAgICAgOnN0cm9rZVdlaWdodD1cIjEwXCJcbiAgICAgICAgQGNsaWNrPVwiY2xpY2tcIlxuICAgICAgLz5cbiAgICA8L2VsLWFtYXA+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwidG9vbGJhclwiPlxuICAgIDxidXR0b24gQGNsaWNrPVwidG9nZ2xlVmlzaWJsZVwiPlxuICAgICAge3sgcG9seWxpbmUudmlzaWJsZSA/ICfpmpDol4/moIforrAnIDogJ+aYvuekuuagh+iusCcgfX1cbiAgICA8L2J1dHRvbj5cbiAgICA8YnV0dG9uIEBjbGljaz1cImNoYW5nZURyYWdnYWJsZVwiPlxuICAgICAge3sgcG9seWxpbmUuZHJhZ2dhYmxlID8gJ+emgeatouagh+iusOenu+WKqCcgOiAn5YWB6K645qCH6K6w56e75YqoJyB9fVxuICAgIDwvYnV0dG9uPlxuICAgIDxidXR0b24gQGNsaWNrPVwiY2hhbmdlRWRpdGFibGVcIj5cbiAgICAgIHt7IHBvbHlsaW5lLmVkaXRhYmxlID8gJ+WBnOatoue8lui+kScgOiAn5byA5aeL57yW6L6RJyB9fVxuICAgIDwvYnV0dG9uPlxuXG4gICAgPHNlbGVjdCB2LW1vZGVsPVwibGluZUpvaW5cIiBAY2hhbmdlPVwib25MaW5lSm9pbkNoYW5nZVwiPlxuICAgICAgPG9wdGlvbiB2YWx1ZT1cIm1pdGVyXCI+bWl0ZXI8L29wdGlvbj5cbiAgICAgIDxvcHRpb24gdmFsdWU9XCJyb3VuZFwiPnJvdW5kPC9vcHRpb24+XG4gICAgICA8b3B0aW9uIHZhbHVlPVwiYmV2ZWxcIj5iZXZlbDwvb3B0aW9uPlxuICAgIDwvc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZiwgcmVhY3RpdmV9IGZyb20gXCJ2dWVcIjtcbmltcG9ydCB7RWxBbWFwLCBFbEFtYXBQb2x5bGluZX0gZnJvbSBcIkB2dWVtYXAvdnVlLWFtYXBcIjtcblxuY29uc3Qgem9vbSA9IHJlZigxMyk7XG5jb25zdCBsaW5lSm9pbiA9IHJlZignbWl0ZXInKVxuY29uc3QgY2VudGVyID0gcmVmKFsxMjEuNTI3MzI4NSwgMzEuMjU1MTUwNDRdKTtcbmNvbnN0IHBvbHlsaW5lID0gcmVhY3RpdmUoe1xuICBwYXRoOiBbWzEyMS41Mzg5Mzg1LCAzMS4yMTUxNTA0NF0sIFsxMjEuNTM4OTM4NSwgMzEuMjk2MTUwNDRdLCBbMTIxLjUyNzMyODUsIDMxLjIxNTE1MDQ0XV0sXG4gIGVkaXRhYmxlOiBmYWxzZSxcbiAgdmlzaWJsZTogdHJ1ZSxcbiAgZHJhZ2dhYmxlOiBmYWxzZVxufSk7XG5jb25zdCBjbGlja01hcCA9IChlKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdjbGljayBtYXA6ICcsIGUpO1xufVxuXG5jb25zdCBvbkxpbmVKb2luQ2hhbmdlID0gKCkgPT4ge1xuY29uc29sZS5sb2coJ29uTGluZUpvaW5DaGFuZ2U6JywgbGluZUpvaW4udmFsdWUpO1xufVxuY29uc3QgaW5pdE1hcCA9IChtYXApID0+IHtcbiAgY29uc29sZS5sb2coJ2luaXQgbWFwOiAnLCBtYXApO1xufVxuY29uc3QgdG9nZ2xlVmlzaWJsZSA9ICgpID0+IHtcbiAgcG9seWxpbmUudmlzaWJsZSA9ICFwb2x5bGluZS52aXNpYmxlO1xufVxuY29uc3QgY2hhbmdlRWRpdGFibGUgPSAoKSA9PiB7XG4gIHBvbHlsaW5lLmVkaXRhYmxlID0gIXBvbHlsaW5lLmVkaXRhYmxlO1xufVxuY29uc3QgY2hhbmdlRHJhZ2dhYmxlID0gKCkgPT4ge1xuICBwb2x5bGluZS5kcmFnZ2FibGUgPSAhcG9seWxpbmUuZHJhZ2dhYmxlO1xufVxuY29uc3QgY2xpY2sgPSAoZSkgPT4ge1xuICBhbGVydCgnY2xpY2sgR2VvSlNPTicpO1xufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJAdnVlbWFwL3Z1ZS1hbWFwL2dsb2JhbC5kLnRzXCIsXCJAdnVlbWFwL3Z1ZS1hbWFwLWxvY2EvZ2xvYmFsLmQudHNcIixcIkB2dWVtYXAvdnVlLWFtYXAtZXh0cmEvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwiaW5jbHVkZVwiOiBbXCJ0eXBpbmdzLyoqLypcIl0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwidHlwaW5ncy9nbGJhbC5kLnRzIjoiZGVjbGFyZSBjb25zdCBBTWFwOiBhbnlcbmRlY2xhcmUgY29uc3QgTG9jYTogYW55XG4iLCJfbyI6e319

**Comment by yangyanggu** [comment]
贴一下代码吧，看下怎么使用的

**Comment by hanlinkan** [comment]
代码地址：https://amap-run.guyixi.cn/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cIm1hcC1wYWdlLWNvbnRhaW5lclwiPlxuICAgIDxlbC1hbWFwXG4gICAgICA6c2hvdy1sYWJlbD1cImZhbHNlXCJcbiAgICAgIDpjZW50ZXI9XCJjZW50ZXJcIlxuICAgICAgOnpvb209XCJ6b29tXCJcbiAgICAgIEBjbGljaz1cImNsaWNrTWFwXCJcbiAgICAgIEBpbml0PVwiaW5pdE1hcFwiXG4gICAgPlxuICAgICAgPGVsLWFtYXAtcG9seWxpbmVcbiAgICAgICAgOmVkaXRhYmxlPVwicG9seWxpbmUuZWRpdGFibGVcIlxuICAgICAgICA6dmlzaWJsZT1cInBvbHlsaW5lLnZpc2libGVcIlxuICAgICAgICA6ZHJhZ2dhYmxlPVwicG9seWxpbmUuZHJhZ2dhYmxlXCJcbiAgICAgICAgOnBhdGg9XCJwb2x5bGluZS5wYXRoXCJcbiAgICAgICAgOmxpbmUtam9pbj1cImxpbmVKb2luXCJcbiAgICAgICAgOnN0cm9rZVdlaWdodD1cIjEwXCJcbiAgICAgICAgQGNsaWNrPVwiY2xpY2tcIlxuICAgICAgLz5cbiAgICA8L2VsLWFtYXA+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwidG9vbGJhclwiPlxuICAgIDxidXR0b24gQGNsaWNrPVwidG9nZ2xlVmlzaWJsZVwiPlxuICAgICAge3sgcG9seWxpbmUudmlzaWJsZSA/ICfpmpDol4/moIforrAnIDogJ+aYvuekuuagh+iusCcgfX1cbiAgICA8L2J1dHRvbj5cbiAgICA8YnV0dG9uIEBjbGljaz1cImNoYW5nZURyYWdnYWJsZVwiPlxuICAgICAge3sgcG9seWxpbmUuZHJhZ2dhYmxlID8gJ+emgeatouagh+iusOenu+WKqCcgOiAn5YWB6K645qCH6K6w56e75YqoJyB9fVxuICAgIDwvYnV0dG9uPlxuICAgIDxidXR0b24gQGNsaWNrPVwiY2hhbmdlRWRpdGFibGVcIj5cbiAgICAgIHt7IHBvbHlsaW5lLmVkaXRhYmxlID8gJ+WBnOatoue8lui+kScgOiAn5byA5aeL57yW6L6RJyB9fVxuICAgIDwvYnV0dG9uPlxuXG4gICAgPHNlbGVjdCB2LW1vZGVsPVwibGluZUpvaW5cIiBAY2hhbmdlPVwib25MaW5lSm9pbkNoYW5nZVwiPlxuICAgICAgPG9wdGlvbiB2YWx1ZT1cIm1pdGVyXCI+bWl0ZXI8L29wdGlvbj5cbiAgICAgIDxvcHRpb24gdmFsdWU9XCJyb3VuZFwiPnJvdW5kPC9vcHRpb24+XG4gICAgICA8b3B0aW9uIHZhbHVlPVwiYmV2ZWxcIj5iZXZlbDwvb3B0aW9uPlxuICAgIDwvc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZiwgcmVhY3RpdmV9IGZyb20gXCJ2dWVcIjtcbmltcG9ydCB7RWxBbWFwLCBFbEFtYXBQb2x5bGluZX0gZnJvbSBcIkB2dWVtYXAvdnVlLWFtYXBcIjtcblxuY29uc3Qgem9vbSA9IHJlZigxMyk7XG5jb25zdCBsaW5lSm9pbiA9IHJlZignbWl0ZXInKVxuY29uc3QgY2VudGVyID0gcmVmKFsxMjEuNTI3MzI4NSwgMzEuMjU1MTUwNDRdKTtcbmNvbnN0IHBvbHlsaW5lID0gcmVhY3RpdmUoe1xuICBwYXRoOiBbWzEyMS41Mzg5Mzg1LCAzMS4yMTUxNTA0NF0sIFsxMjEuNTM4OTM4NSwgMzEuMjk2MTUwNDRdLCBbMTIxLjUyNzMyODUsIDMxLjIxNTE1MDQ0XV0sXG4gIGVkaXRhYmxlOiBmYWxzZSxcbiAgdmlzaWJsZTogdHJ1ZSxcbiAgZHJhZ2dhYmxlOiBmYWxzZVxufSk7XG5jb25zdCBjbGlja01hcCA9IChlKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdjbGljayBtYXA6ICcsIGUpO1xufVxuXG5jb25zdCBvbkxpbmVKb2luQ2hhbmdlID0gKCkgPT4ge1xuY29uc29sZS5sb2coJ29uTGluZUpvaW5DaGFuZ2U6JywgbGluZUpvaW4udmFsdWUpO1xufVxuY29uc3QgaW5pdE1hcCA9IChtYXApID0+IHtcbiAgY29uc29sZS5sb2coJ2luaXQgbWFwOiAnLCBtYXApO1xufVxuY29uc3QgdG9nZ2xlVmlzaWJsZSA9ICgpID0+IHtcbiAgcG9seWxpbmUudmlzaWJsZSA9ICFwb2x5bGluZS52aXNpYmxlO1xufVxuY29uc3QgY2hhbmdlRWRpdGFibGUgPSAoKSA9PiB7XG4gIHBvbHlsaW5lLmVkaXRhYmxlID0gIXBvbHlsaW5lLmVkaXRhYmxlO1xufVxuY29uc3QgY2hhbmdlRHJhZ2dhYmxlID0gKCkgPT4ge1xuICBwb2x5bGluZS5kcmFnZ2FibGUgPSAhcG9seWxpbmUuZHJhZ2dhYmxlO1xufVxuY29uc3QgY2xpY2sgPSAoZSkgPT4ge1xuICBhbGVydCgnY2xpY2sgR2VvSlNPTicpO1xufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJAdnVlbWFwL3Z1ZS1hbWFwL2dsb2JhbC5kLnRzXCIsXCJAdnVlbWFwL3Z1ZS1hbWFwLWxvY2EvZ2xvYmFsLmQudHNcIixcIkB2dWVtYXAvdnVlLWFtYXAtZXh0cmEvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwiaW5jbHVkZVwiOiBbXCJ0eXBpbmdzLyoqLypcIl0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwidHlwaW5ncy9nbGJhbC5kLnRzIjoiZGVjbGFyZSBjb25zdCBBTWFwOiBhbnlcbmRlY2xhcmUgY29uc3QgTG9jYTogYW55XG4iLCJfbyI6e319


***@***.***
 
发件人： yangyanggu
发送时间： 2024-03-27 14:05
收件人： yangyanggu/vue-amap
抄送： Polyxena Johnson; Author
主题： Re: [yangyanggu/vue-amap] ElAmapPolyline组件的“lineJoin”、“lineCap”属性响应式不生效 (Issue #77)
贴一下代码吧，看下怎么使用的

**Comment by yangyanggu** [comment]
你这传的值不对啊，看文档，能接受的值固定的

**Comment by hanlinkan** [comment]
没问题啊：下拉选择就是miter、round、bevel三个值啊

**Comment by yangyanggu** [comment]
我试了下是会更新的啊，不过在顶点那一小块，区别不是太明显

**Comment by hanlinkan** [comment]
默认值改为round是这个样式，区别挺大的
https://amap-run.guyixi.cn/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cIm1hcC1wYWdlLWNvbnRhaW5lclwiPlxuICAgIDxlbC1hbWFwXG4gICAgICA6c2hvdy1sYWJlbD1cImZhbHNlXCJcbiAgICAgIDpjZW50ZXI9XCJjZW50ZXJcIlxuICAgICAgOnpvb209XCJ6b29tXCJcbiAgICAgIEBjbGljaz1cImNsaWNrTWFwXCJcbiAgICAgIEBpbml0PVwiaW5pdE1hcFwiXG4gICAgPlxuICAgICAgPGVsLWFtYXAtcG9seWxpbmVcbiAgICAgICAgOmVkaXRhYmxlPVwicG9seWxpbmUuZWRpdGFibGVcIlxuICAgICAgICA6dmlzaWJsZT1cInBvbHlsaW5lLnZpc2libGVcIlxuICAgICAgICA6ZHJhZ2dhYmxlPVwicG9seWxpbmUuZHJhZ2dhYmxlXCJcbiAgICAgICAgOnBhdGg9XCJwb2x5bGluZS5wYXRoXCJcbiAgICAgICAgOmxpbmUtam9pbj1cImxpbmVKb2luXCJcbiAgICAgICAgOnN0cm9rZVdlaWdodD1cIjEwXCJcbiAgICAgICAgQGNsaWNrPVwiY2xpY2tcIlxuICAgICAgLz5cbiAgICA8L2VsLWFtYXA+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwidG9vbGJhclwiPlxuICAgIDxidXR0b24gQGNsaWNrPVwidG9nZ2xlVmlzaWJsZVwiPlxuICAgICAge3sgcG9seWxpbmUudmlzaWJsZSA/ICfpmpDol4/moIforrAnIDogJ+aYvuekuuagh+iusCcgfX1cbiAgICA8L2J1dHRvbj5cbiAgICA8YnV0dG9uIEBjbGljaz1cImNoYW5nZURyYWdnYWJsZVwiPlxuICAgICAge3sgcG9seWxpbmUuZHJhZ2dhYmxlID8gJ+emgeatouagh+iusOenu+WKqCcgOiAn5YWB6K645qCH6K6w56e75YqoJyB9fVxuICAgIDwvYnV0dG9uPlxuICAgIDxidXR0b24gQGNsaWNrPVwiY2hhbmdlRWRpdGFibGVcIj5cbiAgICAgIHt7IHBvbHlsaW5lLmVkaXRhYmxlID8gJ+WBnOatoue8lui+kScgOiAn5byA5aeL57yW6L6RJyB9fVxuICAgIDwvYnV0dG9uPlxuXG4gICAgPHNlbGVjdCB2LW1vZGVsPVwibGluZUpvaW5cIiBAY2hhbmdlPVwib25MaW5lSm9pbkNoYW5nZVwiPlxuICAgICAgPG9wdGlvbiB2YWx1ZT1cIm1pdGVyXCI+bWl0ZXI8L29wdGlvbj5cbiAgICAgIDxvcHRpb24gdmFsdWU9XCJyb3VuZFwiPnJvdW5kPC9vcHRpb24+XG4gICAgICA8b3B0aW9uIHZhbHVlPVwiYmV2ZWxcIj5iZXZlbDwvb3B0aW9uPlxuICAgIDwvc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZiwgcmVhY3RpdmV9IGZyb20gXCJ2dWVcIjtcbmltcG9ydCB7RWxBbWFwLCBFbEFtYXBQb2x5bGluZX0gZnJvbSBcIkB2dWVtYXAvdnVlLWFtYXBcIjtcblxuY29uc3Qgem9vbSA9IHJlZigxMyk7XG5jb25zdCBsaW5lSm9pbiA9IHJlZigncm91bmQnKVxuY29uc3QgY2VudGVyID0gcmVmKFsxMjEuNTI3MzI4NSwgMzEuMjU1MTUwNDRdKTtcbmNvbnN0IHBvbHlsaW5lID0gcmVhY3RpdmUoe1xuICBwYXRoOiBbWzEyMS41Mzg5Mzg1LCAzMS4yMTUxNTA0NF0sIFsxMjEuNTM4OTM4NSwgMzEuMjk2MTUwNDRdLCBbMTIxLjUyNzMyODUsIDMxLjIxNTE1MDQ0XV0sXG4gIGVkaXRhYmxlOiBmYWxzZSxcbiAgdmlzaWJsZTogdHJ1ZSxcbiAgZHJhZ2dhYmxlOiBmYWxzZVxufSk7XG5jb25zdCBjbGlja01hcCA9IChlKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdjbGljayBtYXA6ICcsIGUpO1xufVxuXG5jb25zdCBvbkxpbmVKb2luQ2hhbmdlID0gKCkgPT4ge1xuY29uc29sZS5sb2coJ29uTGluZUpvaW5DaGFuZ2U6JywgbGluZUpvaW4udmFsdWUpO1xufVxuY29uc3QgaW5pdE1hcCA9IChtYXApID0+IHtcbiAgY29uc29sZS5sb2coJ2luaXQgbWFwOiAnLCBtYXApO1xufVxuY29uc3QgdG9nZ2xlVmlzaWJsZSA9ICgpID0+IHtcbiAgcG9seWxpbmUudmlzaWJsZSA9ICFwb2x5bGluZS52aXNpYmxlO1xufVxuY29uc3QgY2hhbmdlRWRpdGFibGUgPSAoKSA9PiB7XG4gIHBvbHlsaW5lLmVkaXRhYmxlID0gIXBvbHlsaW5lLmVkaXRhYmxlO1xufVxuY29uc3QgY2hhbmdlRHJhZ2dhYmxlID0gKCkgPT4ge1xuICBwb2x5bGluZS5kcmFnZ2FibGUgPSAhcG9seWxpbmUuZHJhZ2dhYmxlO1xufVxuY29uc3QgY2xpY2sgPSAoZSkgPT4ge1xuICBhbGVydCgnY2xpY2sgR2VvSlNPTicpO1xufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG48L3N0eWxlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJAdnVlbWFwL3Z1ZS1hbWFwL2dsb2JhbC5kLnRzXCIsXCJAdnVlbWFwL3Z1ZS1hbWFwLWxvY2EvZ2xvYmFsLmQudHNcIixcIkB2dWVtYXAvdnVlLWFtYXAtZXh0cmEvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwiaW5jbHVkZVwiOiBbXCJ0eXBpbmdzLyoqLypcIl0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwidHlwaW5ncy9nbGJhbC5kLnRzIjoiZGVjbGFyZSBjb25zdCBBTWFwOiBhbnlcbmRlY2xhcmUgY29uc3QgTG9jYTogYW55XG4iLCJfbyI6e319



***@***.***
 
发件人： yangyanggu
发送时间： 2024-03-27 15:26
收件人： yangyanggu/vue-amap
抄送： Polyxena Johnson; Author
主题： Re: [yangyanggu/vue-amap] ElAmapPolyline组件的“lineJoin”、“lineCap”属性响应式不生效 (Issue #77)
我试了下是会更新的啊，不过在顶点那一小块，区别不是太明显

**Comment by yangyanggu** [comment]
这个修改后其实已经更新了，但地图本身没更新，必须放大缩小下地图才会更新，所以这块别用动态更新吧，如果需要可以给高德提下工单处理

**Comment by hanlinkan** [comment]
我发现是高德的BUG，属性修改后没有立即生效，缩放地图之后才会生效



***@***.***
 
发件人： yangyanggu
发送时间： 2024-03-27 15:26
收件人： yangyanggu/vue-amap
抄送： Polyxena Johnson; Author
主题： Re: [yangyanggu/vue-amap] ElAmapPolyline组件的“lineJoin”、“lineCap”属性响应式不生效 (Issue #77)
我试了下是会更新的啊，不过在顶点那一小块，区别不是太明显
