### ISSUE TITLE
@vuemap/vue-amap/dist/style.css必须加载吗？

### ISSUE THREAD

**Issue by hi-noikiy** [yangyanggu/vue-amap#78]
### 使用版本
请填写使用版本：2.1.1

### 问题描述
没有在全局加载，只在单文件里引入了，现在奇怪的问题出现了：
必须加上
```
import '@vuemap/vue-amap/dist/style.css'
```
不然报错
![image](https://github.com/yangyanggu/vue-amap/assets/32630320/c9e1ad4f-8fe2-40db-8c75-bb7b556aab36)

**Comment by yangyanggu** [comment]
是必须加载的，地图必须有高度，css文件中，预置了地图容器的高度

**Comment by hi-noikiy** [comment]
大佬你这速度比群聊都快啊

**Comment by hi-noikiy** [comment]
> 是必须加载的，地图必须有高度，css文件中，预置了地图容器的高度

明白了
