### ISSUE TITLE
el-amap-search-box无法正常使用

### ISSUE THREAD

**Issue by Hao-Wu** [yangyanggu/vue-amap#8]
Vue: 2.6.12
vue-amap: 0.1.7

使用el-amap-search-box，搜索框可以显示出来，但是输入搜索关键词，会发送搜索请求，但是suggesiton list不显示，dom里面也没有。

**Comment by yangyanggu** [comment]
你有没有配置安全密钥，还有如果是弹出框的话会被盖住

**Comment by Hao-Wu** [comment]
确定是`securityJsCode`的问题了。谢谢。
