### ISSUE TITLE
为什么我拖拽地图上面标注有延迟。

### ISSUE THREAD

**Issue by momoca** [yangyanggu/vue-amap#81]
### 使用版本
请填写使用版本：2.0

### 问题描述
如何让标注和地图能同步移动，我是按这个（https://vue-amap.guyixi.cn/zh-cn/component/marker/text.html）例子做的。

https://github.com/yangyanggu/vue-amap/assets/11501193/5efc5966-fd74-404b-a8b0-9bbc31ccf073

**Comment by yangyanggu** [comment]
你弄个在线示例吧，看着是你拖拽的时候修改了text的位置

**Comment by momoca** [comment]
谢谢提示 是 父级 有css 的 transition。引起的。
