### ISSUE TITLE
使用的是vue3报vue2的错

### ISSUE THREAD

**Issue by VCCICCV** [yangyanggu/vue-amap#82]
### 使用版本
请填写使用版本：
vue3
        "@amap/amap-jsapi-loader": "^1.0.1",
        "@vuemap/vue-amap": "^2.1.2",
        "@vuemap/vue-amap-extra": "^2.1.2",
        "@vuemap/vue-amap-loca": "^2.1.1",
### 问题描述
页面代码为
<template>
	<div id="map-container">
		<el-amap :center="[106.5424, 37.9848]" :zoom="7.6">
			<el-amap-loca>
				<custom-loca />
			</el-amap-loca>
		</el-amap>
	</div>
</template>

<script>

</script>

<style scoped>
#map-container{
	width: 100%;
	height:750rpx;
}
</style>
报错
02:17:01.340 "openBlock" is not exported by "node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js", imported by "../../../../../C:/Users/chaochen/Desktop/manyou/haohaomanyoufront/node_modules/@vuemap/vue-amap/es/packages/amap/amap.vue2.mjs".
02:17:01.352 at node_modules/@vuemap/vue-amap/es/packages/amap/amap.vue2.mjs:1:67
02:17:01.363   1: import { defineComponent, provide, ref, nextTick, onBeforeUnmount, openBlock, createElementBlock, createElementVNode,...
02:17:01.374                                                                         ^
02:17:01.385   2: import '../../mixins/index.mjs';
02:17:01.396   3: import guid from '../../utils/guid.mjs';
这个问题在uview最开始引入的时候也有，重启hbuildx几次之后就没有了，现在这个问题一直解决不了

**Comment by yangyanggu** [comment]
你这是在uniapp的模板中使用了组件？组件库没有对uniapp做适配处理
