### ISSUE TITLE
为什么poi搜索的出来的省没有location

### ISSUE THREAD

**Issue by Haif-07** [yangyanggu/vue-amap#83]
### 使用版本
请填写使用版本：@laster

### 问题描述
我是靠这个location修改地图的中心。
![image](https://github.com/yangyanggu/vue-amap/assets/58282852/8c790112-704d-41d1-9594-5c0b26d3b717)

**Comment by yangyanggu** [comment]
poi是靠高德维护数据的，不是每个搜索都能有结果，这边需要判断下，如果没有经纬度，还需要使用地理解析，把返回的位置解析成经纬度

**Comment by Haif-07** [comment]
搞定！感谢
