### ISSUE TITLE
Loca的PulseLine组件visible属性响应式控制显隐失效

### ISSUE THREAD

**Issue by EdwardLiu601** [yangyanggu/vue-amap#84]
### 使用版本
请填写使用版本：
"@vuemap/vue-amap": "2.1.2",
"@vuemap/vue-amap-loca": "2",
JSAPI: "2.0"

### 问题描述
Loca轨迹线图层PulseLineLayer的visible属性的值只有初始化时有效
响应式切换无法改变其状态，官网基础实例里的显示隐藏按钮也无效

**Comment by yangyanggu** [comment]
loca组件的BUG，晚上修复下

**Comment by yangyanggu** [comment]
使用2.1.2版本，已修复该问题

**Comment by EdwardLiu601** [comment]
问题已解决，感谢答复
