### ISSUE TITLE
使用el-amap-marker-cluster 点聚合组件没有鼠标悬浮事件

### ISSUE THREAD

**Issue by rose-lele** [yangyanggu/vue-amap#89]
### 使用版本
请填写使用版本：
latest
### 问题描述

点聚合就是说除了点击事件以外，可不可以增加一个鼠标悬浮事件，我觉得不光是点击事件，悬浮在地图中也是很常用的事件

**Comment by yangyanggu** [comment]
这个我加不了，对于事件我只是转发给高德JSAPI，需要去高德那边提需求

**Comment by yangyanggu** [comment]
如果你实在需要，可以变通的方法实现，就是使用render参数，自己实现聚合点和普通点的绘制，在render函数内对marker对象绑定鼠标事件

**Comment by rose-lele** [comment]
好的，谢谢了
