### ISSUE TITLE
高德地图标题

### ISSUE THREAD

**Issue by hujinhuahjh** [yangyanggu/vue-amap#90]
### 使用版本
请填写使用版本：
最新
### 问题描述
高德地图里不能像百度地图一样设置标题吗

`
option = {
        title: {
          text: '设备分布图',
          subtext: 'fastbee open source iot platform',
          sublink: 'https://iot.fastbee.cn',
          target: '_blank',
          textStyle: {
            color: '#333',
            textBorderColor: '#fff',
            textBorderWidth: 10,
          },
          top: 10,
          left: 'center',
        },
        ...
}
`

**Comment by yangyanggu** [comment]
你这个标题是啥功能，百度地图我也没见过这玩意啊

**Comment by hujinhuahjh** [comment]
> 你这个标题是啥功能，百度地图我也没见过这玩意啊

![https://iot.fastbee.cn/index](https://hjh-oss.oss-cn-shenzhen.aliyuncs.com/public/temp/PixPin_2024-07-24_18-09-54.png)

佬，就是图中的这种效果，如果没有的话，是要用CustomLayer去实现吗

**Comment by yangyanggu** [comment]
这种不就是普通的div盖在地图上么，直接一个absolute div放上去不就行了

**Comment by hujinhuahjh** [comment]
> 这种不就是普通的div盖在地图上么，直接一个absolute div放上去不就行了

这种我知道，就是想看看有没有这种API能用，谢谢佬
