### ISSUE TITLE
使用amap-manager提示AMapManager is not a constructor

### ISSUE THREAD

**Issue by cejpo001** [yangyanggu/vue-amap#91]
### 使用版本
请填写使用版本：vue@2.7.1,@vuemap/vue-amap@2.1.2

### 问题描述
 使用提示  AMapManager is not a constructor

 
![QQ截图20240731122714](https://github.com/user-attachments/assets/54c22a2a-b00f-43a2-b644-8c190910b37f)

**Comment by yangyanggu** [comment]
vue2版本的 @vuemap/vue-amap应该用0.x版本，然后我这个组件库没有AmapManager，那是vue-amap组件库内置的

**Comment by cejpo001** [comment]
哦哦，感谢回答，项目是VUE2的，升级到3的话工作量考虑到不太值，@vuemap/vue-amap的0.x版本没有安全密钥的配置项吧？

**Comment by yangyanggu** [comment]
都有，vue2跟vue3的版本相比，除了少点组件，其他的基本差不多
