### ISSUE TITLE
使用高德的逆地理编码 Geocoder 插件

### ISSUE THREAD

**Issue by hujinhuahjh** [yangyanggu/vue-amap#92]
### 使用版本
请填写使用版本：
最新
### 问题描述
想使用高德地图的逆地理编码插件 Geocoder： `const geocoder = new AMap.Geocoder();`
提示：`Vue: Property Geocoder does not exist on type typeof AMap`

**Comment by yangyanggu** [comment]
我抽时间完善下Geocoder的类型

**Comment by yangyanggu** [comment]
@vuemap/amap-jsapi-types 使用最新版本0.0.18
