### ISSUE TITLE
lazyAMapApiLoaderInstance 如何使用

### ISSUE THREAD

**Issue by 8debug** [yangyanggu/vue-amap#94]
[文档来源](https://vue-amap.guyixi.cn/zh-cn/introduction/compatible.html#promise)
按我对文档的理解，main.ts 中这么写
![image](https://github.com/user-attachments/assets/045e9920-42cf-43c6-9c28-79803e2cdd94)

在home.vue中定义的DOM元素
![image](https://github.com/user-attachments/assets/d93c8798-9e8c-4535-bdec-e43545268086)

### 刷新页面报错
![image](https://github.com/user-attachments/assets/f39fd13b-775f-4153-9695-df73561a429d)

**Comment by yangyanggu** [comment]
肯定不是这么写，lazy是提供一个安全获取AMap对象的回调钩子，这个方法必须在真正使用地图的vue文件中的onMounted中去执行，在lazy的回调方法中进行原生地图的初始化，但更推荐用组件方式加载地图。如果一定要用原生写，更推荐高德本身的加载器

**Comment by 8debug** [comment]
好的，多谢
