### ISSUE TITLE
目前是不支持英文配置吗，我没有找到相关的配置

### ISSUE THREAD

**Issue by donaixiami** [yangyanggu/vue-amap#97]
### 使用版本
请填写使用版本：
最新版
### 问题描述

目前是不支持英文配置吗，我没有找到相关的配置

**Comment by yangyanggu** [comment]
高德jsapi2.0本身不支持英文了，如果需要只能降级用1.4.15

**Comment by donaixiami** [comment]
就是说这个组件降级到用1.4.15版本就可以用英文配置了对吧

**Comment by donaixiami** [comment]
我在初始化脚本时使用1.4.15版本jsapi,的话有英文配置方法吗？

**Comment by donaixiami** [comment]
> 高德jsapi2.0本身不支持英文了，如果需要只能降级用1.4.15

就是说这个组件降级到用1.4.15版本就可以用英文配置了对吧
我在初始化脚本时使用1.4.15版本jsapi，的话有英文配置方法吗？

**Comment by yangyanggu** [comment]
那倒不行，组件库是基于2.0开发的，降级使用1.4.15的话，API会报错比较多，1.4.15比较推荐其他库，如果实在需要，可以再el-amap的extraOptions加一个 {lang: 'en'}试试，但后续其他组件使用报错概率极大，不是太推荐

**Comment by donaixiami** [comment]
> 那倒不行，组件库是基于2.0开发的，降级使用1.4.15的话，API会报错比较多，1.4.15比较推荐其他库，如果实在需要，可以再el-amap的extraOptions加一个 {lang： 'en'}试试，但后续其他组件使用报错概率极大，不是太推荐

好的
